### ISSUE TITLE
cloud_in topic not available on doing rostopic list

### ISSUE THREAD

**Issue by SubMishMar** [ros-perception/pointcloud_to_laserscan#18]
I launched the following launch file to run pointcloud_to_laserscan_node but could not find the `cloud_in` topic which is used to input  pointcloud data into the node
<?xml version="1.0"?>

<launch>

    
    <node pkg="pointcloud_to_laserscan" type="pointcloud_to_laserscan_node" name="pointcloud_to_laserscan">
        <rosparam>
            target_frame: camera_link # Leave disabled to output scan in pointcloud frame
            transform_tolerance: 0.01
            min_height: 0.0
            max_height: 1.0

            angle_min: -1.5708 # -M_PI/2
            angle_max: 1.5708 # M_PI/2
            angle_increment: 0.0087 # M_PI/360.0
            scan_time: 0.3333
            range_min: 0.45
            range_max: 4.0
            use_inf: true
            inf_epsilon: 1.0

            # Concurrency level, affects number of pointclouds queued for processing and number of threads used
            # 0 : Detect number of cores
            # 1 : Single threaded
            # 2->inf : Parallelism level
            concurrency_level: 1
        </rosparam>

    </node>

</launch>

On doing a rostopic list with this launch file running, the following topics were listed.
`/clock
/rosout
/rosout_agg
/scan
/tf
/tf_static
`

How can input point cloud to the node?

**Comment by paulbovbel** [comment]
https://github.com/ros-perception/pointcloud_to_laserscan/blob/lunar-devel/src/pointcloud_to_laserscan_nodelet.cpp#L119

Because of the 'lazy subscriber'/pipeline pattern used in this node, `cloud_in` will only be registered once another component subscribes to `scan`.

So try `rostopic echo /scan` followed by `rostopic list`.

Please reopen this issue if you discover any problems with the implementation.

**Comment by SubMishMar** [comment]
Seems to work atm! Thanks @paulbovbel .
